### ISSUE TITLE
The current CA expires in August 2024 and doesn't support automatic server certificate rotation

### ISSUE THREAD

**Issue by yury-liberau-workday** [robbiet480/rds-ca#1]
The current CA expires in **August 2024** and doesn't support automatic server certificate rotation

In December 2022, AWS released new CA certificates that are valid for 40 years (rds-ca-rsa2048-g1):
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html

A certificate bundle that contains both the intermediate and root certificates for all AWS Regions is available at https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem.

It will be great if this can be updated into the project.

Many Thanks!

**Comment by yury-liberau-workday** [comment]
I've opened this PR, would be nice if it is updated :)

https://github.com/robbiet480/rds-ca/pull/2

**Comment by robbiet480** [comment]
Published updated certificates as version 2.0.0. Thanks again @yury-liberau-workday!
